<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Trick;

/**
 * CommentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return the list of comment with all associated entities.
     *
     * @param Trick $trick
     * @param int   $limit
     * @param int   $offset
     *
     * @return array the list of comment
     */
    public function findWithAllEntities(Trick $trick): array
    {
        return $this->createQueryBuilder('c')
            ->innerJoin('c.user', 'u')
            ->addSelect('u')
            ->innerJoin('c.trick', 't')
            ->addSelect('t')
            ->where('t.id = :id')
            ->setParameter('id', $trick->getId())
            ->orderBy('c.date', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
