<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Trick;

/**
 * TrickRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return a trick with all associated entities.
     *
     * @param string $slug
     *
     * @return Trick|null
     */
    public function findWithAllEntities(string $slug): ?Trick
    {
        return $this->createQueryBuilder('t')
            ->leftJoin('t.user', 'u')
            ->addSelect('u')
            ->andWhere('t.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
