<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recovers a user by token.
     *
     * @param string $token
     *
     * @return User|null
     */
    public function getUserWithToken(string $token): User
    {
        $token = $this->sanitizeToken($token);

        $user = $this->createQueryBuilder('u')
            ->where('u.token = :token')
            ->setParameter('token', $token)
            ->getQuery()
            ->getOneOrNullResult()
        ;

        // If the user doesn't exist
        if (!$user) {
            throw new \LogicException(
                sprintf('L\'utilisateur n\'existe pas! Avez-vous bien suivi le lien envoyé par email!')
            );
        }

        return $user;
    }

    /**
     * Recovers a user with email.
     *
     * @param string $email
     *
     * @return User|null
     */
    public function getUserWithEmail(string $email): ?User
    {
        $email = $this->sanitizeEmail($email);

        return $this->createQueryBuilder('u')
            ->where('u.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    /**
     * The token The token is a 64 character hexadecimal string.
     *
     * @param string $token
     */
    public function sanitizeToken(string $token)
    {
        if (preg_match('#^[0-9a-f]{64}$#', $token)) {
            return $token;
        }
        // If the token isn't valide
        throw new \LogicException(
            sprintf('Le token fourni n\'est pas valide!')
        );
    }

    /**
     * Sanitize an email.
     *
     * @param string $email
     */
    public function sanitizeEmail(string $email)
    {
        return filter_var($email, FILTER_SANITIZE_EMAIL);
    }
}
