# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        # Admin inherits user rights
        ROLE_ADMIN:       [ROLE_USER]
        
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:      AppBundle\Entity\User
                property:   username
    
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  true
            provider:   main
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_token_generator: security.csrf.token_manager
            logout_on_user_change: true
            logout:
                path:       /logout
                target:     /